
name: JPG Mover


on:

  push:
    paths: '**.jpg'
  pull_request:
    paths: '**.jpg'

jobs:
  move-jpg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for Folder
        run: |
          if [ ! -d “/Images”]
          then
            mkdir -p Images
          fi

      - name: Move .jpg file
        run: mv *.jpg Images
        
      - name: Add user info and commit changes
        run: git config user.name 'DanielBrett'
             git config user.email 'dbrett@brocku.ca'
             git add .
             git commit -m "JPG Mover Activated"
             git push
